# Generated by Django 3.2.5 on 2021-08-01 19:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('account_type', models.CharField(choices=[('STANDARD', 'Standard cash or margin account'), ('TFSA', 'Tax-Free Savings Account'), ('RRSP', 'Registered Retirement Savings Plan')], default='STANDARD', max_length=12)),
                ('currency', models.CharField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'U.S. Dollar')], default='CAD', max_length=3)),
                ('cash_position', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='EquityHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=8)),
                ('first_added_at', models.DateTimeField(auto_now_add=True)),
                ('cumulative_units', models.DecimalField(decimal_places=6, default=0, max_digits=32)),
                ('cumulative_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('last_ask_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('holdings_value', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('exchange', models.CharField(blank=True, max_length=32)),
                ('dividend_yield', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('dividend_schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3), default=list, size=None)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
