# Generated by Django 3.2.5 on 2021-08-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityholding',
            name='holdings_value',
        ),
    ]
